### PR TITLE
Add arcade color mod

### PR DESCRIPTION
**Pull request by neurorulez**
A simple mod who some pll make to the atari kee sprint cabinets.

sprint1

### CODE REVIEW

**Comment by suverman** [comment]
Thanks!!!!!!

**Comment by alanswx** [comment]
There should be 3 yellow cars  and a green one in Sprint1 - the mame version is broken. There shouldn't be a blue car.

**Comment by alanswx** [comment]
I fixed it..

**Comment by neurorulez** [comment]
Ok, but i dont use the mame source, i follow the instructions of a friend than say to me the conexions on the board make in the 70s to convert the arcade sprint2 to rgb. I translate the same.to sprint1. Realy the machine have separate atributes for that cars, and can be converted in diferent colors. Only the persom who make the mod in the motherboard choose the correct one. Its good to get diferent colors in both cores. ;) Looks good.

**Comment by alanswx** [comment]
James who built the simulation pointed out originally that sprint 1 is 1 player so only 1 car is a different color. Easy mod to make the color version the same.

**Comment by alanswx** [comment]
Thanks for doing the color hack! It works great.

**Comment by sorgelig** [comment]
To me it looks like talk between 2 color-blind people :)
Game was monochrome originally. How you can know which exactly color should be?

**Comment by ghost** [comment]
https://www.arcade-museum.com/game_detail.php?game_id=9740

I think inspiration from Sprint 4

**Pull request merged**
